# coding: utf-8

"""
Copyright 2015 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class CreditCardCharge(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        CreditCardCharge - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'amount': 'float',
            'tax_amount': 'float',
            'currency': 'str',
            'credit_card': 'str',
            'installments': 'float',
            'order_id': 'str',
            'description': 'str',
            'third_party_id': 'str',
            'paid': 'bool',
            'customer': 'str',
            'payment_transaction': 'str'
        }

        self.attribute_map = {
            'id': 'id',
            'amount': 'amount',
            'tax_amount': 'taxAmount',
            'currency': 'currency',
            'credit_card': 'creditCard',
            'installments': 'installments',
            'order_id': 'orderId',
            'description': 'description',
            'third_party_id': 'thirdPartyId',
            'paid': 'paid',
            'customer': 'customer',
            'payment_transaction': 'paymentTransaction'
        }

        self._id = None
        self._amount = None
        self._tax_amount = None
        self._currency = None
        self._credit_card = None
        self._installments = None
        self._order_id = None
        self._description = None
        self._third_party_id = None
        self._paid = None
        self._customer = None
        self._payment_transaction = None

    @property
    def id(self):
        """
        Gets the id of this CreditCardCharge.


        :return: The id of this CreditCardCharge.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this CreditCardCharge.


        :param id: The id of this CreditCardCharge.
        :type: str
        """
        self._id = id

    @property
    def amount(self):
        """
        Gets the amount of this CreditCardCharge.


        :return: The amount of this CreditCardCharge.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """
        Sets the amount of this CreditCardCharge.


        :param amount: The amount of this CreditCardCharge.
        :type: float
        """
        self._amount = amount

    @property
    def tax_amount(self):
        """
        Gets the tax_amount of this CreditCardCharge.


        :return: The tax_amount of this CreditCardCharge.
        :rtype: float
        """
        return self._tax_amount

    @tax_amount.setter
    def tax_amount(self, tax_amount):
        """
        Sets the tax_amount of this CreditCardCharge.


        :param tax_amount: The tax_amount of this CreditCardCharge.
        :type: float
        """
        self._tax_amount = tax_amount

    @property
    def currency(self):
        """
        Gets the currency of this CreditCardCharge.
        3-letter ISO code for currency.

        :return: The currency of this CreditCardCharge.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """
        Sets the currency of this CreditCardCharge.
        3-letter ISO code for currency.

        :param currency: The currency of this CreditCardCharge.
        :type: str
        """
        self._currency = currency

    @property
    def credit_card(self):
        """
        Gets the credit_card of this CreditCardCharge.


        :return: The credit_card of this CreditCardCharge.
        :rtype: str
        """
        return self._credit_card

    @credit_card.setter
    def credit_card(self, credit_card):
        """
        Sets the credit_card of this CreditCardCharge.


        :param credit_card: The credit_card of this CreditCardCharge.
        :type: str
        """
        self._credit_card = credit_card

    @property
    def installments(self):
        """
        Gets the installments of this CreditCardCharge.
        The amount of payments to divide the charge amount.

        :return: The installments of this CreditCardCharge.
        :rtype: float
        """
        return self._installments

    @installments.setter
    def installments(self, installments):
        """
        Sets the installments of this CreditCardCharge.
        The amount of payments to divide the charge amount.

        :param installments: The installments of this CreditCardCharge.
        :type: float
        """
        self._installments = installments

    @property
    def order_id(self):
        """
        Gets the order_id of this CreditCardCharge.


        :return: The order_id of this CreditCardCharge.
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id):
        """
        Sets the order_id of this CreditCardCharge.


        :param order_id: The order_id of this CreditCardCharge.
        :type: str
        """
        self._order_id = order_id

    @property
    def description(self):
        """
        Gets the description of this CreditCardCharge.


        :return: The description of this CreditCardCharge.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this CreditCardCharge.


        :param description: The description of this CreditCardCharge.
        :type: str
        """
        self._description = description

    @property
    def third_party_id(self):
        """
        Gets the third_party_id of this CreditCardCharge.


        :return: The third_party_id of this CreditCardCharge.
        :rtype: str
        """
        return self._third_party_id

    @third_party_id.setter
    def third_party_id(self, third_party_id):
        """
        Sets the third_party_id of this CreditCardCharge.


        :param third_party_id: The third_party_id of this CreditCardCharge.
        :type: str
        """
        self._third_party_id = third_party_id

    @property
    def paid(self):
        """
        Gets the paid of this CreditCardCharge.


        :return: The paid of this CreditCardCharge.
        :rtype: bool
        """
        return self._paid

    @paid.setter
    def paid(self, paid):
        """
        Sets the paid of this CreditCardCharge.


        :param paid: The paid of this CreditCardCharge.
        :type: bool
        """
        self._paid = paid

    @property
    def customer(self):
        """
        Gets the customer of this CreditCardCharge.


        :return: The customer of this CreditCardCharge.
        :rtype: str
        """
        return self._customer

    @customer.setter
    def customer(self, customer):
        """
        Sets the customer of this CreditCardCharge.


        :param customer: The customer of this CreditCardCharge.
        :type: str
        """
        self._customer = customer

    @property
    def payment_transaction(self):
        """
        Gets the payment_transaction of this CreditCardCharge.


        :return: The payment_transaction of this CreditCardCharge.
        :rtype: str
        """
        return self._payment_transaction

    @payment_transaction.setter
    def payment_transaction(self, payment_transaction):
        """
        Sets the payment_transaction of this CreditCardCharge.


        :param payment_transaction: The payment_transaction of this CreditCardCharge.
        :type: str
        """
        self._payment_transaction = payment_transaction

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()
