# coding: utf-8

"""
Copyright 2015 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class DaviPlataVerification(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        DaviPlataVerification - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'davi_plata': 'str',
            'pin_number': 'str'
        }

        self.attribute_map = {
            'davi_plata': 'daviPlata',
            'pin_number': 'pinNumber'
        }

        self._davi_plata = None
        self._pin_number = None

    @property
    def davi_plata(self):
        """
        Gets the davi_plata of this DaviPlataVerification.


        :return: The davi_plata of this DaviPlataVerification.
        :rtype: str
        """
        return self._davi_plata

    @davi_plata.setter
    def davi_plata(self, davi_plata):
        """
        Sets the davi_plata of this DaviPlataVerification.


        :param davi_plata: The davi_plata of this DaviPlataVerification.
        :type: str
        """
        self._davi_plata = davi_plata

    @property
    def pin_number(self):
        """
        Gets the pin_number of this DaviPlataVerification.


        :return: The pin_number of this DaviPlataVerification.
        :rtype: str
        """
        return self._pin_number

    @pin_number.setter
    def pin_number(self, pin_number):
        """
        Sets the pin_number of this DaviPlataVerification.


        :param pin_number: The pin_number of this DaviPlataVerification.
        :type: str
        """
        self._pin_number = pin_number

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()
